server:
  port: ${SERVER_PORT}

spring:
  application:
    name: main
  config:
    import: optional:environment.properties
  data:
    mongodb:
      uri: mongodb://${MONGO_SERVER}:${MONGO_PORT}/${MONGO_DATABASE}

springdoc:
  swagger-ui:
    filter: true
    operationsSorter: method
    displayRequestDuration: true
    syntaxHighlight.theme: arta
    persistAuthorization: true
    doc-expansion: none
