name: "CI: Main Backend"

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - "backend/main/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Infrastructure Preparation
      run: docker-compose up -d

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.11"

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./backend/main/gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./backend/main
      env:
        MONGO_SERVER: ${{secrets.MONGO_SERVER}}
        MONGO_PORT: ${{secrets.MONGO_PORT}}
        MONGO_DATABASE: ${{secrets.MONGO_DATABASE}}

    - name: Run Tests
      run: ./gradlew test
      working-directory: ./backend/main
      continue-on-error: true

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ./backend/main/build/test-results/test
          ./backend/main/build/reports/tests/test

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Generate and submit dependency graph
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.11"
        
